libraries:
	cd trie; make library
	cd util; make library
clean:
	cd trie; make distclean
	cd util; make distclean
	cd apps; make clean
maxchain:
	cd apps; make maxchain
subwords:
	cd apps; make subwords